### PR TITLE
Introduce normalization

### LINKED ISSUE #3: Add method which returns proper envelope label

### PR DESCRIPTION
**Pull request by patrys**
Fixes #3

This changes the API entirely. New API is as follows:

```python
address = {
    'country_code': 'US',
    'country_area': 'California',
    'postal_code': '94037',
    'city': 'Mountain View',
    'street_address': '1600 Charleston Rd.'}

get_validation_rules(address)
# ValidationRules(
#     allowed_fields={'country_area', 'company_name', 'postal_code', 'street_address', 'city', 'name'},
#     required_fields={'postal_code', 'country_area', 'city', 'street_address'},
#     upper_fields={'country_area', 'city'},
#     country_area_type='state',
#     country_area_choices=[('AL', 'AL'), ('AK', 'AK'), ('AS', 'AS'), ..., ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')],
#     city_type='city',
#     city_choices=[],
#     city_area_type='suburb',
#     city_area_choices=[],
#     postal_code_matchers=[
#         re.compile('^(\\d{5})(?:[ \\-](\\d{4}))?$'),
#         re.compile('^9[0-5]|96[01]')],
#     postal_code_examples='90000,96199',
#     postal_code_type='zip')


normalize_address(address)
# {'city': 'MOUNTAIN VIEW',
#  'city_area': '',
#  'country_area': 'CA',
#  'country_code': 'US',
#  'postal_code': '94037',
#  'street_address': '1600 Charleston Rd.'}
```

### CODE REVIEW

**Comment by patrys** [comment]
I intend to only use `<select>` for country selection. I want to use the various `*_choices` fields to populate a client-side autocomplete using [`<datalist>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist).

**Comment by patrys** [comment]
I also want to always render all fields even if not allowed for a particular country with extra fields being rendered as hidden. This way picking an address from a different country will still fill them before we rerender/revalidate.

**Comment by mociepka** [comment]
@patrys can we get in `postal_code_examples` list?

**Comment by mociepka** [comment]
Please update the readme file. We need to cover all its use cases with new API.

**Comment by patrys** [comment]
I don't really have the time to update the README now.

Providing postal code examples as a list is a separate feature, examples can contain ranges so it's not a trivial task.

**Pull request merged**
